services:
    car.data_checker:
        class: CarBundle\Service\DataChecker
        arguments: ["@doctrine.orm.entity_manager", "%required_photos_to_promote_car%"]
        #arguments: ["@service_id", "plain_value", "%parameter%"]

    car.command.abc:
        class: CarBundle\Command\AbcCheckCarCommand
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: console.command}
